---
- hosts: kuber
  become: yes  

  tasks:
    - name: Install git service
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
          
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd.io
        state: latest

    - name: Enable docker-ce
      service:
        name: docker
        state: started
        update_cache: yes

    - name: Add user in group Docker
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: present

- hosts: srv
  become: yes

  tasks:
    - name: Install Java
      ansible.builtin.apt:
        pkg: 
        - fontconfig 
        - openjdk-17-jre 
        state: present
        update_cache: true
    
    - name: Add key Jenkins
      ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present
    
    - name: Add Repository Jenkins
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
    
    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: latest
        update_cache: yes
      
